### ISSUE TITLE
There is problem with the WinAppDriver finding the right elements on Virtuell Machine

### ISSUE THREAD

**Issue by Saif4** [microsoft/WinAppDriver#1002]
Sometimes when I run my tests on VM the WinAppDriver does not find the correct element, It finds something random but very close to my element that I want, is someone else has experienced this issue? It only happens on VM

**Comment by licanhua** [comment]
How do you locate the elements? Are you using xpath? Do you wait enough time for the UI to be updated complete?
You may get PageSource each time you are locating the concerned element, then to see if you can find something interesting.

**Comment by Saif4** [comment]
I use Name or AutomationID and I have enough time to wait,. The driver finds the right element because it will fails either way. For exempel if I have a drop down with 3 alternatives and I want to select the middle one, but sometimes its finds the first or the third instead. Next time I run the test it works

**Comment by fenchu** [comment]
I see the same issue, if my widgets do not comply to good UX designs (I test it with https://accessibilityinsights.io/docs/en/windows/overview to find discrepancies). winappdriver may be extremely slow to find stuff and often return something that fails.
After we started using accessibilityInsights in development to test widgets, this issue is minimized.
I use python and find winappdriver to be horrendously slow compared to commercial products like Smartbears TestComplete.

**Comment by Saif4** [comment]
A quick fix is I restart my VM and everything  works again. ¯\_(ツ)_/¯
