### ISSUE TITLE
Value attribute and Text is not working in XPath 

### ISSUE THREAD

**Issue by Pratiky2j007** [microsoft/WinAppDriver#1164]
ControlType = DataItem
    Name = 'Identifier'
    ValuePattern.Value = 'Text'
    LegacyIAccessiblePattern.Value = 'Text'
    AutomationId = blank
I tried using text

**Comment by Tree55Topz** [comment]
You have to first instantiate the element before you can access those properties. So if the Name attribute has the identifier you would first create that WindowsElement...

`WindowsElement element = session.FindElementByAccessibilityId("Identifier")`

And then you can grab the ValuePattern.Value attribute like so...

`string elementText = element.GetAttribute("ValuePattern.Value");`

Also, including a screenshot of what you are picking up with the spy tool and the xpath code you tried would be even more helpful.

**Comment by Pratiky2j007** [comment]
I am trying to find a windows element using value attribute
FindElementByXPath("//DataItem[@Value='XXXXXXX']");
It is giving exception

**Comment by Pratiky2j007** [comment]
> You have to first instantiate the element before you can access those properties. So if the Name attribute has the identifier you would first create that WindowsElement...
> 
> `WindowsElement element = session.FindElementByName("Identifier")`
> 
> And then you can grab the ValuePattern.Value attribute like so...
> 
> `string elementText = element.GetAttribute("ValuePattern.Value");`
> 
> Also, including a screenshot of what you are picking up with the spy tool and the xpath code you tried would be even more helpful.

**Comment by Tree55Topz** [comment]
I have not been successful in using the Value.Value properties in XPath as well, which leads me to believe that they can not reliably be used as such. In order to get these values you first need to identify it using Class, Name, AutomationID, etc (the core properties). From your first post you said Name = 'Identifier'.. does this mean that you can just use the FindElementByName approach? If thats the case that would be much better than using XPath.

If FindElementByName is going to return more than one element and that is why you are resorting to XPath and the ValuePattern.Value property, what you can do is use FindElementsByName or FindElementsByAccessibilityId to return an array of elements and then loop through them to find a match on the ValuePattern.Value attribute. Like this example below (C#)

```
var elements = session.FindElementsByName("Identifier");

foreach (var element in elements){
       if (element.GetAttribute("ValuePattern.Value").Equals("Identifier")){
                WindowsElement clickable = (WindowsElement)element;
                element.Click();
       }
}
```
Keep in mind this approach can be slow if you are returning a large array of elements, if not then this should be fine.

**Comment by Pratiky2j007** [comment]
Thanks yes that help

**Comment by Tan-Thanh** [comment]
How I can get 'Text' from "ValuePattern.Value"? I tried element.get_attribute (in Python) but not worked

**Comment by liljohnak** [comment]
@Tan-Thanh have you tried the `.Text` property?

**Comment by Tan-Thanh** [comment]
> @Tan-Thanh have you tried the `.Text` property?

Thank you. It works for me.
