### ISSUE TITLE
Is there any way to Draw-Outlines for WinApp Element ?

### ISSUE THREAD

**Issue by Heidernlee** [microsoft/WinAppDriver#1395]
As the following image, Is there any way to draw outlines for
WinApp Element so I can capture this screenshot with a Red Frame ?
like XXElement.draw_outlines() or something else ? 

![111](https://user-images.githubusercontent.com/25810034/101711749-2b0f5b00-3acf-11eb-9d1f-fd2e145bdd2b.png)

**Comment by liljohnak** [comment]
Yes, it took a bit of work to create though.
.CaptureImage() to a bitmap, then overlay the outline.

**Comment by licanhua** [comment]
Agreed. It's not a big task and you can do it.
Here are Java code snippets, and you can combine them together easily.

https://www.toolsqa.com/selenium-webdriver/screenshot-in-selenium/
```
   // Get screenshot of the visible part of the web page
        File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        
        // Convert the screenshot into BufferedImage
        BufferedImage fullScreen = ImageIO.read(screenshot);
        
        //Find location of the webelement logo on the page
        Point location = logo.getLocation();
        
        //Find width and height of the located element logo
        int width = logo.getSize().getWidth();
        int height = logo.getSize().getHeight();
```

https://stackoverflow.com/questions/11634867/drawing-filled-rectangle-over-a-bufferedimage
```
Graphics2D graph = img.createGraphics();
graph.setColor(Color.BLACK);
graph.fill(new Rectangle(x, y, width, height));
graph.dispose();
        
ImageIO.write(img, "jpg", new File("images/template.jpg"));
```

**Comment by Heidernlee** [comment]
@liljohnak @licanhua 
liljohnak, also nice to meet you here ^_^
Thanks for your response. As your comments It's easy to write a red border for a full-screenshot,
but what I want is one window-screenshot ,with many red tags for some Elements (like buttons, labels, text-inputs ),
so I can cut these Elements out what tagged, and save them as small Images ,using Open-CV.
and I know WinAppDriver can capture a screenshot for one-single-Element.....
But one windows-screenshot with many red tags ? seems not OK.

Here's the new comment :
BTW, PyWinAuto is also a Tool for run Windows App automatically,
It contains a method called [draw-out-lines] for one-element ,seems is changed element's style.
Does WinAppDriver can only read element's style but cannot change any of them ?

**Comment by licanhua** [comment]
I don't think WinAppDriver supports the style change, and I doubt if UIA supports this interface.
For PyWinAuto, I think PyWinAuto draws the [outline](https://github.com/pywinauto/pywinauto/blob/187b84de20f7980d4f5cff4abdb3bbff17cc049e/pywinauto/controls/win_base_wrapper.py#L82) by itself, not changing the style. 

If your application is running inside Explorer like Edge and Chrome, then yes, it's allowed to change styles, because it's allowed to Execute Javascript to modify styles for any element. Also I know there are existing tools to do it

If your goal is to capture screenshot for a single element which doesn't include other window parts, try [this tool and hit this endpoint](https://github.com/licanhua/YWinAppDriver/blob/178d6be92d03dc039fceaa98f5994a3e903a76eb/src/WinAppDriver/Controllers/SessionController.cs#L334) 

If your goal is add a lot of red rectangles on the same screenshot, then the simplest way I know is: take a screenshot, get the locations of the concerned elements, and draw rectangles on the screenshot by yourself.

**Comment by Heidernlee** [comment]
@licanhua 
Thanks for your response , 
I'll try the way that you mentioned. It's a good one, Thanks again

And could you kindly please check the following Issue ? It also drives me crazy ...
https://github.com/microsoft/WinAppDriver/issues/1398

**Comment by licanhua** [comment]
WinAppDriver has its own xpath parser and xpath implementation, so I have no knowledge to answer your question.

**Comment by Heidernlee** [comment]
@licanhua  Thanks, I'll keep working on it..... Case closed
