### ISSUE TITLE
SetText function for WinAppDriver

### ISSUE THREAD

**Issue by matt-stratt** [Microsoft/WinAppDriver#1616]
Is there anyway with WinAppDriver to SetText? I know that SendKeys can be used for data entry, but in a lot of cases for generic text fields, SetText would be way quicker.

Not sure if anyone has implemented a way to do this? I saw some other examples online of using the C# Clipboard classes and using a threaded approach but I would like to avoid that if possible.

**Comment by Tree55Topz** [comment]
Right, im pretty sure there is ways to do this with selenium for web, here for example https://sqa.stackexchange.com/questions/7085/regarding-setting-text-of-a-webelement-without-using-sendkeys-method

The benefit would be to cut down on execution time because SendKeys can be slow at times, especially when entering a lot of fields. This would just set the value all at once without typing each character.

**Comment by Shakevg** [comment]
@Tree55Topz You can try to use my variant of copy-paste #1194 (comment)

**Comment by Tree55Topz** [comment]
@Shakevg thats a great example, thanks!
