### ISSUE TITLE
Launching UWP app with activated args

### ISSUE THREAD

**Issue by Pebin** [Microsoft/WinAppDriver#166]
When UWP app is able to start with URI "registered" in the OnActivated method, is it somehow possible to specify this URI for example in DeviceCapabilities?

In my case I would like to bypass an identification screen which requires additional input which I don't have when writing unit test.

It's kind of similar to issue/question #29

**Comment by timotiusmargo** [comment]
Hi @Pebin, 

Since [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). Windows Application Driver can now launch an application with command line arguments. Below is an example of starting **Microsoft Edge** on a given URL specified as launching parameter.

```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge");
appCapabilities.SetCapability("appArguments", "about:blank");
WindowsDriver<WindowsElement> session = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), appCapabilities);
```

The snippet above is taken from [CreateSessionWithArguments_ModernApp](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Session.cs#L326) test scenario. Would you please give it a try and reopen if you encountered any issue?
