### ISSUE TITLE
Cannot toggle soft keyboard on windows surface pro

### ISSUE THREAD

**Issue by tangyanhan** [Microsoft/WinAppDriver#168]
Finally I managed to start an app on tablet. But I have not found a way to toggle soft keyboard on a windows 10 surface pro after inputting text with send_keys. 
When the keyboard is shown on screen, elements behind the keyboard can neither be found nor operated. 
Hope someone could help me with this issue.

**Comment by hassanuz** [comment]
Closing issue due to time gap. 

A way to bring up the virtual keyboard using SendKeys is the following (tested on Windows 10 RS4) : 

`            editBox.SendKeys(Keys.Command + Keys.Control + "o"); 
`
This will simulate the following key strokes - "Windows + CRTL + O".  

The reason why elements behind the keyboard cannot be interacted upon could be that the keyboard is stealing focus from the target app - to workaround this would be to simply dismiss the keyboard with the same keystrokes prior to resuming automation.
