### ISSUE TITLE
how to set startup dir for win32 app?

### ISSUE THREAD

**Issue by congzhangzh** [Microsoft/WinAppDriver#176]
As title, how to set startup dir info in the capability?

**Comment by timotiusmargo** [comment]
Since [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). Windows Application Driver can now launch a classic windows app with **command line arguments** and **application working directory**. Below is an example of launching **Notepad** opening `MyTestFile.txt` in `C:\MyTestFolder\` working directory.

```c#
// Launch Notepad
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
appCapabilities.SetCapability("appArguments", @"MyTestFile.txt");
appCapabilities.SetCapability("appWorkingDir", @"C:\MyTestFolder\");
WindowsDriver<WindowsElement> NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
```

The snippet above is taken from [CreateSessionWithWorkingDirectoryAndArguments](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Session.cs#L353) test scenario. Check out the [README.md](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#supported-capabilities) for more information on other supported capabilities.
