### ISSUE TITLE
Button visible to Inspect, but not accessible through WinAppDriver

### ISSUE THREAD

**Issue by eoyslebo** [Microsoft/WinAppDriver#210]
I am trying to access the New Case button of an app called Griffeye.

I can see the button in Inspect, but it is not accessible through WinnAppDriver/Appium (using RobotFramework).

The only result when searching for "New Case" in the the output of Log Source is the entry from Inspect. If Inspect is not running, there are no search results for "New Case" in the XML output.

Any advice? RobotFramework, Appium and Griffeye are all launched as Adminstrator, so I don't think it's a permission issue.

Edit: uploaded test file and output. Also: using Root to get a "Desktop session" because Griffeye takes a long time to load and I want to reuse the running session.

[Log Source.xml.txt](https://github.com/Microsoft/WinAppDriver/files/1096273/Log.Source.xml.txt)
[windows_griffeyetest.txt](https://github.com/Microsoft/WinAppDriver/files/1096276/windows_griffeyetest.txt)

**Comment by eoyslebo** [comment]
![inspect](https://user-images.githubusercontent.com/1457947/27457044-135e5cd8-579b-11e7-981f-7b30993709bd.png)

**Comment by eoyslebo** [comment]
RobotFramework test:

`
*** Settings ***
Library           AppiumLibrary
Library           DebugLibrary

Test Setup        Open Application  ${REMOTE_URL}  platformName=Windows  deviceName=WindowsPC  app=${APP}  automationName=appium
Test Teardown    Close Application

*** Variables ***
${REMOTE_URL}     http://localhost:4723/wd/hub
${APP}             Root


*** Test Cases ***
Initialize
    [Documentation]    (reusing running app)
    Log Source
    #Debug

`

**Comment by eoyslebo** [comment]
Possibly related to https://github.com/Microsoft/WinAppDriver/issues/83.

This looks to be a WinForms application.

**Comment by PandaMagnus** [comment]
I've seen cases in several different automation tools in two main scenarios:
1) It's either a control using the much older MSAA technology (which seems likely, the provider in Inspect is MSAA Proxy)
2) It's a custom control that, in any case, is not implementing the UIAutomation library.

In the first case, or the second where it's implementing MSAA, I've seen success with clicking on the control first via a vector. It's messy, but if you get the parent control first (if it can be found) helps minimize the inherent fragility of that solution. Once the click is complete, I've been able to find some problem controls (although not always with the same information listed in Inspect.)

In the second case, if neither UIA or MSAA is implemented (which is unlikely since Inspect found it,) you're pretty hosed.

As a note, I've seen this behavior coding with White, FlaUI (both sitting on the UIAutomation library,) and CodedUI (which uses both UIA and MSAA.) I'm going to give this a shot with WinAppDriver the first chance I get. :)

**Comment by hassanuz** [comment]
Hi @eoyslebo,
We were not identifying items that did not have a runtimeID in the past. This has been addressed in our v1.0 release. Can you please try the latest version and let us know if it works.
Thanks

**Comment by hassanuz** [comment]
Marking issue as closed due to no further comments.
