### ISSUE TITLE
Finding element by tag name is not implemented. 

### ISSUE THREAD

**Issue by camillake** [Microsoft/WinAppDriver#222]
By sending http POST request: /session/:sessionid/element with request body {"using":"tag name","value":"text"}

I got the error message.
{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

I can see the element in the source, but it can not be scanned by above command.
<Text AcceleratorKey=\"\" AccessKey=\"\" AutomationId=\"\" ClassName=\"TextBlock\" FrameworkId=\"WPF\" HasKeyboardFocus=\"False\" HelpText=\"\" IsContentElement=\"True\" IsControlElement=\"True\" IsEnabled=\"True\" IsKeyboardFocusable=\"False\" IsOffscreen=\"False\" IsPassword=\"False\" IsRequiredForForm=\"False\" ItemStatus=\"\" ItemType=\"\" ***LocalizedControlType=\"text\"*** Name=\"\" Orientation=\"None\" ProcessId=\"220\" RuntimeId=\"7.220.38888871\" x=\"71\" y=\"8\" width=\"98\" height=\"16\" />

**Comment by yodurr** [comment]
it looks like your element's Name is blank.  It's the Name attribute that query will be checking.

**Comment by timotiusmargo** [comment]
Hi @camillake,

Finding element by tag name is indeed implemented. In the element you described above, you would need to send `Text` instead of `text` in the request body as follows:
```
{"using":"tag name","value":"Text"}
```

In C#, the code above is generated through the following command:
```c#
WindowsElement element = session.FindElementByTagName("Text");
```

You can find similar example on our [FindElement_ByTagName](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Element.cs#L72) sample test.
