### ISSUE TITLE
FindElementByAccessibilityId is not implemented in selenium python

### ISSUE THREAD

**Issue by camillake** [Microsoft/WinAppDriver#223]
selenium python version:3.4.3

**Comment by timotiusmargo** [comment]
Hi @camillake,

Selenium clients are generally written for the web counterpart where **Accessibility Id** is not relevant. You should use the Appium clients which are the extension of the Selenium ones with more app specific features. For instance, you can use the [Appium Python Client](https://github.com/appium/python-client) to test an app with the Python language binding. They also have a readme section showing how to [find element(s) by accessibility id](https://github.com/appium/python-client/tree/v0.14#finding-elements-by-accessibility-id) using their library.

**Comment by Rami1940** [comment]
I am copying the code from Appium Inspector and pasting in my IntelliJ where I use Java to write my script. I always must modify the Appium notation so that I can write my script using TestNg annotation, like I can't use findEelementByAccessibilty and instead I must change it to find element by id then I copy the id and use it. Is there a library I can use to automatedly use findElementByAccessibilty rather than modify to findElementById?
