### ISSUE TITLE
How to launch Microsoft Click-Once application

### ISSUE THREAD

**Issue by randikaf** [Microsoft/WinAppDriver#251]
Is there a way to launch an application which bundle with Microsoft Click-Once directly using WinAppDriver (Without directly invoking the .exe)?

**Comment by timotiusmargo** [comment]
Hi @randikaf,

Could you share what happens when you pass the full path of the **link** or `appref-ms` file in the `app` capability?

**Comment by Manvibha** [comment]
I have a similar issue; when I try to invoke a application of appref-ms file, it throws error 

HTTP/1.1 500 Internal Error
Content-Length: 297
Content-Type: application/json
{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\<Path>\\Client.appref-ms, and processId: 25984"}}
Application is opened but fails to create session. 
Below is the code 
              DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", GetApplicationPath("AppPath"));
                appCapabilities.SetCapability("deviceName", "WindowsPC");
                Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);

Regards,
Mahendra

**Comment by timotiusmargo** [comment]
When an **appref-ms** reference file is specified instead of the link or the executable in the **app** capability, your application will be launched through system `rundll32.exe` process. In such case, there’s no practical way for the WinAppDriver to identify the right process id or application window belonging to your application.

I would recommend using the link file or the executable directly if possible. However, if launching using **appref-ms** reference is the only option for your scenario, you can locate the launched window using a [desktop session](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#creating-a-desktop-session) and [create a new session by attaching to the window](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#attaching-to-an-existing-app-window) you found.
