### ISSUE TITLE
Hostname invalid error when running on localhost as non-admin

### ISSUE THREAD

**Issue by jsbakker** [Microsoft/WinAppDriver#271]
I am trying to automate starting winappdriver.exe by spawning a background process from Ruby in my Cucumber script. No problem with spawn, as I have tested using it with other commands.

- The first problem is that I have to run winappdriver.exe as administrator. I looked into runas.exe but that still requires input, so it's bad for scripting. There are other reasons not to chase this.
- The alternative is to use "localhost" as the host, since winappdriver.exe tells me I can run only as localhost without admin privileges.

`winappdriver.exe localhost 4723/wd/hub`

However, when I try to create the Appium webdriver, I get the following error:

```
  unexpected response, code=400, content-type="text/html"
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
  <HTML><HEAD><TITLE>Bad Request</TITLE>
  <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
  <BODY><h2>Bad Request - Invalid Hostname</h2>
  <hr><p>HTTP Error 400. The request hostname is invalid.</p>
  </BODY></HTML> (Selenium::WebDriver::Error::WebDriverError)
```

Now if I just start winappdriver manually as administrator using 127.0.0.1 it works fine...

`winappdriver.exe 127.0.0.1 4723/wd/hub`

..but the problem is that it's not great for fully automating my tests (starting and stopping winappdriver between my Cucumber runs would be nice, instead of the choice of either manual or always on).

Seeing that localhost and 127.0.0.1 are essentially the same, I did not expect an error when using one but not the other.

Thanks.

**Comment by khouzam** [comment]
Hi @jsbakker 

I'm a little confused as to why you need to run `winappdriver.exe 127.0.0.1 4723/wd/hub` as administrator and not as a regular user? 

Also, if you launch an appium test, appium should launch WinAppDriver for you.

**Comment by jsbakker** [comment]
@khouzam This is the output if I run as non-admin:

```
C:\Users\jbakker>winappdriver.exe 127.0.0.1 4723/wd/hub
Windows Application Driver listening for requests at: http://127.0.0.1:4723/wd/hub

Access denied: attempting to add Address 'http://127.0.0.1:4723/wd/hub'. Run as administrator to listen on an hostname other than localhost, or to listen on port 80.

Failed to initialize: 0x80004005
```

After a Windows restart I was able to run it once successfully, but after stopping the server (by pressing ENTER key to exit), I keep getting this message when running as non-admin.

**Comment by khouzam** [comment]
Thanks for the followup @jsbakker 

Can you confirm which build of WinAppDriver you're running?

**Comment by jsbakker** [comment]
I'm pretty sure I downloaded the 1.0 RC .msi from the releases page. The file version of the .exe shows 1.0.1708.10001.

**Comment by inel85** [comment]
Hi jsbakker, 

I'm also confirming the need to start winappdriver as an admin and the issues you described starting with the 2nd run the same version 1.0.1708.10001.

To your error when using hostname instead of the IP => I encountered the same issue in the beginning, unfortunately I can't remember exactly what fixed it, but I managed to overcome it, I'm now able to start winappdriver with 'localhost' or even <hostname> if I use it remotely
          winappdriver.exe localhost 4723

Some useful tips: 
- Be consistent: if you start WinAppDriver with IP, be sure to use the IP as well when initializing the WindowsDriver, in the test project. And viceversa, if you use hostname when starting WinAppDriver, use the hostname as well during driver initialization. 
- I gave up of using '/wd/hub' in 'winappdriver.exe localhost 4723/wd/hub', as an initial workaround for some errors, perhaps exactly for the hostname error. It works just fine for me without the '/wd/hub'

**Question**: 
Did you manage to find a solution for starting and stopping winappdriver between your tests run? It ys, it would be helpful if you post it here, I'm also searching a way.

**Comment by hassanuz** [comment]
Please reopen if this issue persists with the latest [WinAppDriver v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1) release.

**Comment by vagisha-nidhi195** [comment]
@hassanuz I am able to start a session without admin mode with `127.0.0.1` but I am not able to remotely connect to it. I can connect properly when I use the ip address, but unfortunately, using IP needs elevated admin permissions. If I am running in a CI/CD env, I will not be able to get elevated permissions. How do we bypass this?
