### ISSUE TITLE
driver.findElementByAccessibilityId Vs driver.findElementById

### ISSUE THREAD

**Issue by SanjeevKumarmn** [Microsoft/WinAppDriver#276]
Using Java -
What's the difference between the driver.findElementByAccessibilityId Vs driver.findElementById/ driver.findElement(By.id(""))? 

Can we reuse the  selenium modules?
ex: driver.findElement(By.id(APPLICATION_NAME_ID)).click doesn't seems to work and however, the findElementByAccessibilityId  seems to work.

**Comment by timotiusmargo** [comment]
Hi @SanjeevKumarmn,

As described in our list of [supported locators](https://github.com/Microsoft/WinAppDriver/blob/master/README.md#supported-locators-to-find-ui-elements), Appium **AccessibilityId** refers to **AutomationId** of the UI element as shown in the [inspect](https://github.com/Microsoft/WinAppDriver/blob/master/README.md#inspecting-ui-elements) tool. **ElementId** or simply **Id** refers to the unique identifier of the element which in most cases is the **RuntimeId** of the UI element.

Note that non UIA compliant applications may contain elements with no **RuntimeId**. In such case, we will assign a unique **GUID** for the element so that further operation/actions can be performed on this element. Another query to find the same element in however, will result in a different **GUID**.

**Comment by SanjeevKumarmn** [comment]
@timotiusmargo thanks and this really helps!

**Comment by sachinDV** [comment]
From accessibilityId how to get a text value?

**Comment by bessareliance** [comment]
@sachinDV Try to use the command below written in python. 
variable = self.driver.find_element_by_accessibility_id("xxxxxx").text
