### ISSUE TITLE
Not able to GetAttribute on WindowsElement

### ISSUE THREAD

**Issue by PawanSelenium** [Microsoft/WinAppDriver#290]
when I inspect my WPF application. I see some attributes like _BoundingRectangle_:	{l:225 t:56 r:1915 b:997}, _IsOffscreen_:	false , _ClickablePoint_:	{x:1070 y:526}  but in WinAppDriver, either don't get these values or I get default values like empty string or 0 (for numeric values). Could you please advise, what wrong I could have been doing. Please see my code snippet below.

var waitControl = windows_driver.FindElementByAccessibilityId("busyAnimation");
Logger.Debug(
                    waitControl.Displayed, //this always comes false
                    waitControl.Enabled, //this always comes true
                    waitControl.Id, 
                    waitControl.Location, //always {X=0,Y=0}
                    waitControl.GetAttribute("LegacyIAccessible.State"), //always empty string
                    waitControl.GetAttribute("ClickablePoint"), //always  0,0
                    waitControl.Size)); //{Width=0, Height=0}

**Comment by timotiusmargo** [comment]
Hi @PawanSelenium,

I'm not sure what the problem is without having a sample app that reproduce the issue. But before we get to it, can you try generating the page source for your application at that particular time? An example C# command to do this can be found on https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Source.cs

Note that attributes do change along the lifecycle of the application. So each attribute may return you different values if you call it on different application state. The `inspect.exe` does not always refreshed/reloaded to reflect the latest application/UI element state unless you tell it to.

**Comment by AmirHNK** [comment]
Just to share my experience, When I build and launch my WPF application through Visual Studio, inspect app does not show many of the UI a tributes. However when I manually launch the app executable, I can use inspect to read UI elements attributes with no issues.

**Comment by hassanuz** [comment]
Hi @PawanSelenium,

Please feel free to reopen or create a new ticket if this issue still persists.
