### ISSUE TITLE
API /session/:sessionId/click not work

### ISSUE THREAD

**Issue by camillake** [Microsoft/WinAppDriver#309]
OS: windows 10
windriver: v1.0 Release
language: appium python client.

error message: Missing Command Parameter: element

looks like I must assign an element for touch/click event. 
Is it possible that I just send the coordinate without specifying element ?

If I specify an element,  the center of the element always be clicked no matter what coordinate I assign.

**Comment by timotiusmargo** [comment]
Hi @camillake,

I'm not sure what request and payload the Appium Python Client send to WinAppDriver to get the error you reported above. Can you include the `WinAppDriver.exe` command log that gave you the error?

At the same time, can you try our [WebDriverAPI Mouse C# sample test](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L55) code below that should perform the [`session/:sessionId/click`](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidclick) command? E.g.:

```c#
// Implicitly invoke /session/:sessionId/moveto and /session/:sessionId/click
WindowsElement num8Button = session.FindElementByAccessibilityId("num8Button");
session.Mouse.Click(num8Button.Coordinates);

// Explicitly invoke /session/:sessionId/moveto and then /session/:sessionId/click on the current position
WindowsElement clearButton = session.FindElementByAccessibilityId("clearButton");
session.Mouse.MouseMove(clearButton.Coordinates);
session.Mouse.Click(null);
```

As far as I know `element` **is not** a required parameter for `session/:sessionId/click` command. For [session/:sessionId/touch/click](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchclick) on the other hand, `element` **is** a required parameter that you need to provide. However, you can absolutely do a combination of [session/:sessionId/touch/down](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchdown) and [session/:sessionId/touch/up](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchup) in order to simulate similar click action. An example can be found on the following snippet taken from https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L75:

```c#
touchScreen.Down(clearButtonLocation.X, clearButtonLocation.Y);
touchScreen.Up(clearButtonLocation.X, clearButtonLocation.Y);
```

**Comment by camillake** [comment]
@timotiusmargo 
Thanks for your soon reply.
The combination "touch/down & touch/up" works.
I use selenium client to send that request because Appium not implement touch/down & touch/up event.
