### ISSUE TITLE
When would winappdriver extend support for Windows12 or windows16 server 

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#310]
Hi, 

When would winappdriver extend support for Windows12 or windows16 server., since I have service application that run only on Windows 12 server and client running on windows 10.

Thanks,
Mahendra

**Comment by khouzam** [comment]
Hi @Manvibha,

WinAppDriver should work fine on Windows Server 2016 since it shares the same core are Windows 10. Are you seeing issues with it? You will need to enable developer mode on the server to run WinAppDriver.

Can you give a little more details on what you mean by a service application? I'm assuming that you have a UI on the server application as this is what WinAppDriver is interacting with.

Thanks

**Comment by Manvibha** [comment]
thanks for response. I did not attempt on Win2016 machine since it was never mentioned about it (Hope I am right) .  I will give a try and keep you posted for any issues.
Any idea support for Win2012 server ?

Thanks,
Mahendra

**Comment by hassanuz** [comment]
There are no plans to support anything south of Windows 10 or Windows Server 2016.

**Comment by Manvibha** [comment]
hope "south" to be read as "out" from above response??
