### ISSUE TITLE
Status 105 error: Element not interactable

### ISSUE THREAD

**Issue by todoubled711** [Microsoft/WinAppDriver#319]
Hi,

I am receiving a message:

POST /session/7B7A7F4E-D79C-4801-9485-EBBAE6C9E74E/element/7.12172.7025535/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 40
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"class name","value":"TextBox"}
HTTP/1.1 200 OK
Content-Length: 102
Content-Type: application/json

{"sessionId":"7B7A7F4E-D79C-4801-9485-EBBAE6C9E74E","status":0,"value":{"ELEMENT":"7.12172.50983304"}}

==========================================
POST /session/7B7A7F4E-D79C-4801-9485-EBBAE6C9E74E/element/7.12172.50983304/value HTTP/1.1
Accept: application/json, image/png
Content-Length: 28
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":["This is a Test"]}
HTTP/1.1 400 Bad Request
Content-Length: 175
Content-Type: application/json

{"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}

I am not able to use SendKeys() with text into a textbox. Is there a workaround for this?

Thanks,
Todd

**Comment by timotiusmargo** [comment]
Hi @todoubled711,

The error you saw above is intended by design when the test script attempts to type/action on an element that is currently hidden/not visible. Is this not the case? Windows Application Driver should enable your test script to perform anything that the user can do on the application. Typing or clicking on a hidden/non-visible element is not it.

If the **TextBox** you are targetting is in fact visible on the time you execute the send key command, then this error is a bug that we will have to fix. In such case, could you provide the repro steps for this error to occur?
