### ISSUE TITLE
Excel + Open File Dialog - cannot locate address bar element

### ISSUE THREAD

**Issue by gbminnock** [Microsoft/WinAppDriver#479]
Hi,
I am writing some code to interact with excel. I want to open a file using the "Other Other Workbooks" and "Browse" however I am unable to locate the element in the address bar of the Dialog.

`
ExcelSession.findElementByName("Open Other Workbooks").click();
ExcelSession.findElementByName("Browse").click();
ExcelSession.findElementByAccessibilityId("1001").sendKeys("C:\\myexcel.xlsx");
`

I'm not sure if it is located in a different window and I've had a look using inspect.exe but it does seem to be a child of the Excel window. 

Any thoughts on how to get around this would be appreciated.

**Comment by timotiusmargo** [comment]
Hi @gbminnock,

It is likely that your session is currently pointing to a different window (could be the splash screen that appears on the startup) instead of the window you are looking at. You can use the [GetWindowHandle](https://github.com/Microsoft/WinAppDriver/blob/v1.1-RC/Tests/WebDriverAPI/Window.cs#L74) or [GetPageSource](https://github.com/Microsoft/WinAppDriver/blob/v1.1-RC/Tests/WebDriverAPI/Source.cs#L39) and compare the values with the one you see on [inspect tools](https://github.com/Microsoft/WinAppDriver/tree/v1.1-RC#inspecting-ui-elements) to confirm it.

If this is the case, you can simply prevent **Excel** from opening the splash screen when it launches using `/e` argument or write a logic to handle the splash screen as I described below:
https://github.com/Microsoft/WinAppDriver/issues/392#issuecomment-412728379

**Comment by hassanuz** [comment]
Closing issue. Please reopen if you are experiencing this on latest release.
