### ISSUE TITLE
DesiredCapabilities run application in Session ID = 0

### ISSUE THREAD

**Issue by Soloveykos** [Microsoft/WinAppDriver#493]
DesiredCapabilities run application in Session ID = 1 in local environment but when it works in CI with TFS it runs application in Session ID = 0 and the test fails.

![image](https://user-images.githubusercontent.com/42540836/45361022-cefcba00-b5d9-11e8-8c07-3dcb8d7c4d08.png)

Could someone please help with running application in correct session?

I had short investigation: Seems when we start WinAppDriver.exe in session ID = 1 then application will be started also in session 1. In order to start WinAppDriver.exe in session 1 we need to run it physically on environment, or maybe schedule the task for it.

**Comment by hassanuz** [comment]
Hi @Soloveykos,

Can you confirm if your [agent is configured for interactive mode](https://github.com/Microsoft/WinAppDriver/wiki/Continuous-Integration-with-WinAppDriver/5bee38584ade51e0d71ada221a2e9eff707a423b#setting-up-a-custom-agent-to-be-used-for-ui-automation)? 

Session ID = 0  implies that it is setup as a service rather than interactive.

**Comment by Soloveykos** [comment]
The issue is solved. I've just start the WinAppDriver.exe as a Process from the code in AssemblyInitialize. So nothing should be started on TFS. and this probably solved the issue.

**Comment by hassanuz** [comment]
Awesome, thanks for reporting back @Soloveykos.
