### ISSUE TITLE
Failed to locate opened application window with appId because of RintimeBroker running first

### ISSUE THREAD

**Issue by IevgeniiAstanin** [Microsoft/WinAppDriver#503]
**When** I am running my application using WAD on remote machine which is working slowly
**Then** RuntimeBroker running first
**And** I got an error:

```
HTTP/1.1 500 Internal Error
Content-Length: 191
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: '''!App, and processId: 24472"}}
```

**And** Application is runnung in suspended mode, even when this option is switched off in Windows configuration

As I understood WAD is searching for specified window for first sub-process, but when RuntimeBroker is running first and has no window, then I receive this error
![2018-09-27_16h12_38](https://user-images.githubusercontent.com/12794263/46148249-51d77300-c270-11e8-9077-51bf095cc98d.png)

**Comment by HughJohnson69** [comment]
I am running into the same situation. If I run the app debug... then it seems to work fine. -- but when I run normal its like the splash screen starts nut takes too long and the runtime broker suspends the process? 
 any help would be appreciated

**Comment by hassanuz** [comment]
Hi @IevgeniiAstanin and @HughJohnson69  ,

This could be due to the [splash screen ](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#what-to-do-when-an-application-has-a-splash-screen-or-winappdriver-fails-to-recognize-the-correct-window) interfering with the session. Recommend taking a look at the Wiki if you haven't already. 

Can you share which process the processID is referencing?   

Thanks
