### ISSUE TITLE
Inspect.exe not able to inspect the POP up element 

### ISSUE THREAD

**Issue by Dwipro** [microsoft/WinAppDriver#519]
Hi Team,
I was trying to Inspect the pop up element using Inspect.exe tool, but is not able to inspect the element

For ex-  i have user name and Password text and  and ok button , when i am giving one only user name then pressing ok button , one pop will come , for that pop i am trying to click Ok on pop up screen and trying to inspect element of ok button , so that i can validate my test cases , unfortunately inspect.exe unable to inspect the element .

Can any have look on this , why pop screen inspect element not capturing ?

**Comment by hassanuz** [comment]
Hi @Dwipro,

It could be that the pop-up element is not apart of the main application window, and as such you will have to switch to a [desktop session](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-create-a-desktop-session) in order to interact with it.

Can you try the [UI Recorder tool](https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC) to see if it picks up the XPath and share that here? 

Thanks

**Comment by Dwipro** [comment]
That application developed in Xamrin platform and pop is a part of application only , same pop i was able to handle in Android and IOS  and getting the element , i am using python for writing the script . 
i tried UI recorder , i am getting element name , but i tried to give as class name but it doesn't work in my script

**Comment by Dwipro** [comment]
@hassanuz , i have tried all the possibilities, it couldn't work for me . can you please help me ?
