### ISSUE TITLE
Operation Time out error while initiating call to Windows Driver

### ISSUE THREAD

**Issue by KiranBehara** [Microsoft/WinAppDriver#585]
Hi,

Am able to launch the application but it is throwing time-out error immediately & session is returning null value. I tried with time-out parameter but still the same issue.

session = new WindowsDriver(new Uri(WindowsApplicationDriverUrl), appCapabilities, TimeSpan.FromMinutes(2));

FYI - The App i am trying to launch is a thick client, it will take 60-90 minutes to load the screen/modules & also we have a splash screen which appears immediately when we launch our application.

Can someone please help me.

Thank You!

Regards,
Kiran B.

**Comment by timotiusmargo** [comment]
Hi @KiranBehara,

Would you share the logs from the `WinAppDriver.exe` console window showing the time out error you mentioned above?

When it is known that the application will take a really long since the launch until the first main window is open, you should wait and create a session by [attaching to an existing application window](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/a8c02cfac47b4bf0c12c571b6010c403dcfe5e7f#when-and-how-to-attach-to-an-existing-app-window). E.g.
1. Launch application
2. Wait until main application window is open (optionally, you can also inspect the splash screen dialog in the meantime)
3. Once the application window is open, create a new session by attaching to it as shown at the wiki above

**Comment by KiranBehara** [comment]
Thank You. We handled it in catch block and session id is returning now.
