### ISSUE TITLE
How to assert that an element is readonly

### ISSUE THREAD

**Issue by kviji** [microsoft/WinAppDriver#706]
Hi,

I want to assert that an element is readonly and is not editable as a part of my testcase
I tried
        Assert.assertTrue(Web_ELement.getAttribute("readOnly").equals("true"),"Message");

I am getting null pointer exception. I can see from the inspect.exe that the element LegacyAccessible.State is read only and focusable.

**Comment by jgkahua** [comment]
That is because "LegacyAccessible.State" may not be accessible in the element identifiers that the WinAppDriver framework can handle.  

Check out this link for available attributes: https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelementidentifiers?redirectedfrom=MSDN&view=netframework-4.8.

However, coding side, what I would do is something kind of hackish, create a method that tries to input text on a parameterized element and returns true or false depending if the elements.text has changed.

Example: Assert(checkElementIsReadOnly(session.FindElementBy("whatever you want"), "Message");

bool checkElementIsReadOnly(IWebElement element)
{
element.SendKeys("some text");
if (element.GetAttribute("value") != "what ever you type")
return true;
else
return false;
}

**Comment by kviji** [comment]
Hi @jgkahua 

Thats a nice hack and it works. 
Shall use it at the moment until Accessible state is provided. 
Thanks
