### ISSUE TITLE
[Help] How to launch application under test for every test case without creating the new session for winappdriver

### ISSUE THREAD

**Issue by Pverma96** [microsoft/WinAppDriver#737]
I am automating a windows application in Java using winappdriver where I have three test cases and each test needs to launch the application. I am using the below code to initialize the driver and launch the application. 

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app, "appPath");
		capabilities.setCapability("platformName", "windows");
		capabilities.setCapability("deviceName", "windowsPC");
		capabilities.setCapability("appWorkingDir", "XXXXXXXX");
		driver = new WindowsDriver<WebElement>(new URL("http://127.0.0.1:4723"), capabilities);

To launch the application for each test i need to run the above code before every test case. This will result in initialization of driver three times. Though my tests are passing but getting below messages in console window. Note: I am starting the winappdriver programatically. Just want to know what is the best way to handle this situation.

![Console logs](https://user-images.githubusercontent.com/48497443/59887034-ee9deb80-937e-11e9-82b8-9008fe7359a6.PNG)

**Comment by hassanuz** [comment]
You only need to create another app session, but it looks like you're also trying to launch WinAppDriver multiple times. 

Wherever that is in your code, you should limit it to being called once and at the start of test round rather than for each individual test case. 

Closing issue. Please reopen if you have any further questions.
