### ISSUE TITLE
findElementByName or findElementByAccessibilityId not throwing any exception in winappdriver

### ISSUE THREAD

**Issue by MumtazRashid** [microsoft/WinAppDriver#837]
If I pass wrong id or name in winppdriver find element function, It get stop at that step only and test case execution get stuck, Its not showing any exception or failure

**Comment by Rangyia** [comment]
May I gather some information from you in order to debug this?

1.) What IDE are you using?
2.) What is the coding language that you are utilizing?
3.) Are you running the test is 'debug' mode also or are you running this just straight from a 'Test Runner'?

Sometimes this instability can happen due to something outside of WinAppDriver, due to some kind of method call or process within your code where its a run-time execution error.

**Comment by naeemakram** [comment]
Looks like the timeouts are very long in this case. The WinAppDriver console window might print what error had occurred, does it?

**Comment by khoachung89** [comment]
You should first see the WinAppDriver console log first as naeemakram's comment to clarify it's exactly exception of element not found.

The second stuff is checking your code wrappers. Do you add any additional exception handler in code wrapper that handle the exception already? At least, you should check you Exception Settings if you are using Visual studio.
