### ISSUE TITLE
Huge security vulnerability - Passwords are sent to WinAppDriver in plain text

### ISSUE THREAD

**Issue by naeemakram** [microsoft/WinAppDriver#853]
I have just noticed that the password field values are being sent to WinAppDriver as plain text over HTTP. This is a major security flaw and it must be fixed ASAP.

**Comment by NathanZook** [comment]
This is an application focused on testing.  If you are using anything other than an account set up exclusively for testing, and with access to only those things appropriate for testing, you have a bigger problem than network sniffing.

**Comment by naeemakram** [comment]
Our network security team won't buy this I'm afraid :'(

**Comment by hassanuz** [comment]
Hi @naeemakram,

Selenium / Appium / WinAppDriver do not support encryption via SendKeys as per the spec, and this is for various reasons (one being that this will never be secure even with encryption since you will have to pass the client key somehow anyway). 

I would recommend using an exclusive account for testing as Nathan mentioned above.

**Comment by naeemakram** [comment]
All right sure, thanks very much Nathan & Hassan.
