### ISSUE TITLE
Installing WinAppDriver on Windows 10 IoT Core

### ISSUE THREAD

**Issue by scout208** [microsoft/WinAppDriver#860]
I was wondering if it's possible to install WinAppDriver on a Windows 10 IoT Core device so these tests could be run on an IoT Core device.

**Comment by shift-morikawa** [comment]
I've installed on Window10 IoT OS.
And sample-code 'Calc' seems to work collectly with remote connection.([Running on a Remote Machine](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#running-on-a-remote-machine))
But another problem has occuerd,but I think it caused by target application's matter.

**Comment by marcostroppel** [comment]
@shift-morikawa is it Windows 10 IoT Enterprise or Windows 10 IoT Core?

**Comment by hassanuz** [comment]
WinAppDriver does not support IoT core devices at this type due to the omission of UIA APIs needed by WinAppDriver.
