### ISSUE TITLE
Send Multiple Events as a single event

### ISSUE THREAD

**Issue by jacobg12** [microsoft/WinAppDriver#956]
Hi,

I was wondering if it's within scope to send a chain of events to the WinAppDriver, and allow it to execute all of them in sequence?

There's roughly 250 ms or so of a performance delay between each call, and depending on the amount of steps required this can delay a test significantly.

For instance, when attempting to brute force; you're limited by default to the response/translation speed of the service.

If it can be allowed such that you can send a sequence of commands as one command, the WinAppDriver could execute them very fast, one after the other and send back a response once finiched; or once an error is found.

**Comment by hassanuz** [comment]
This isn't naively supported by WinAppDriver, unless if you're using the Actions API in which case you can queue up a [sequence ](https://github.com/microsoft/WinAppDriver/blob/f4449aaad63843311be7fdaeeff48d38ad60f357/Samples/C%23/Paint3DTest/ScenarioDraw.cs#L91)of touch or pen gestures and them be executed at nearly the same time.

**Comment by jacobg12** [comment]
@hassanuz  are you aware of any way to use the Sequence Events item and fire events onto a new window handle?

Or are sequence Events only for the current WindowHandle of the session it's executed on?

**Comment by hassanuz** [comment]
@jacobg12 - you could use a [desktop (root) session](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-create-a-desktop-session) to fire off Touch/Pen sequence handles across varying window handles. I'd try that to see if it does the trick. 

Closing issue due to time gap - but please feel free to reopen if you have any other questions.
