### ISSUE TITLE
Azure CI/CD : WinAppDriver Logs

### ISSUE THREAD

**Issue by VijayHugar** [microsoft/WinAppDriver#967]
I am starting WinAppDriver, executing automation scripts and stopping WinAppDriver as part of Azure Release flow. When my test fails, I wanted to see the WinAppDriver logs. Is there any option available?

**Comment by naeemakram** [comment]
Following

**Comment by hassanuz** [comment]
Hi @VijayHugar, the WinAppdriver Stop task should have the logs in it's output. 

What are you seeing in your output?

**Comment by KevIvers** [comment]
A gotcha re this for me, was the stop task was never running because the test task in between the start and stop task was failing (because of an issue with the winAppdriver starting). Two work arounds I found were, if you are using a private agent, the log file is created in the appropriate task folder under the AzureAgent root folder or set your test projects to continue on error so the stop task runs.

**Comment by hassanuz** [comment]
You can also enable the "Continue on error" flag under Control Options for any Pipelines Task. This will allow you to jump onto the WinAppDriver stop task even if the task prior to it fails.

**Comment by VijayHugar** [comment]
@KevIvers Thanks for your reply! Your suggested work around solved my problem.
