### ISSUE TITLE
Window Handles in WinAppDriver

### ISSUE THREAD

**Issue by JGjumpshot** [microsoft/WinAppDriver#978]
Are window handles supported in WinAppDriver? I have an app launcher that will open the application I'm supposed to be testing and would like to move the focus to that new window. How can I do this?

**Comment by anunay1** [comment]
Yes its supported in WinAppDriver

**Comment by JGjumpshot** [comment]
How is it used?

**Comment by anunay1** [comment]
check #937

**Comment by anunay1** [comment]
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", YourAppId);
WindowsDriver<WindowsElement> session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
Assert.IsNotNull(session);
// Identify the current window handle. You can check through inspect.exe which window this is.
var currentWindowHandle = session.CurrentWindowHandle;
// Wait for 5 seconds or however long it is needed for the right window to appear/for the splash screen to be dismissed
Thread.Sleep(TimeSpan.FromSeconds(5));
// Return all window handles associated with this process/application.
// At this point hopefully you have one to pick from. Otherwise you can
// simply iterate through them to identify the one you want.
var allWindowHandles = session.WindowHandles;
// Assuming you only have only one window entry in allWindowHandles and it is in fact the correct one,
// switch the session to that window as follows. You can repeat this logic with any top window with the same
// process id (any entry of allWindowHandles)
session.SwitchTo().Window(allWindowHandles[0]);

**Comment by JGjumpshot** [comment]
Thank you. I'll give that a try.

**Comment by JGjumpshot** [comment]
[image: image.png]This is the first part of the application I would like to
open. When I open that I get this.
[image: image.png]It won't see any of the elements on this new screen. How
can I switch? I try what you have suggested but when I do an index of [1]
It says that it is out of range.

**Comment by anunay1** [comment]
The that is a separate window, you need to use desktop session with root and then find the topmost window and switch to that window.

**Comment by anunay1** [comment]
You can get info on desktop session from wiki

**Comment by rabaribe** [comment]
Hi,
//I have actual experience using WindowHandlers with Winappdriver
//try the snippet below it will focus on the top window, and then try and find elements after this.

_driver.SwitchTo().Window(_driver.WindowHandles.First());

//Last will focus on the bottom window 
_driver.SwitchTo().Window(_driver.WindowHandles.Last());

**Comment by JGjumpshot** [comment]
Thank you!

**Comment by rabaribe** [comment]
//or try to focus on the next window.

_driver.SwitchTo().Window(_driver.WindowHandles[1]);
